### ISSUE TITLE
'minValue <= value': is not true.

### ISSUE THREAD

**Issue by kehindeegunjobi93** [MarcinusX/NumberPicker#109]
I get this error when I use a number not divisible by 10 (eg. 15) on the min value.

I am currently using 15 to 45 and step is 15.

**Comment by MarcinusX** [comment]
Are you sure that your `value` is greater than `minValue`?

This example with initial `_currentIntValue = 15` works for me.
```
NumberPicker(
  value: _currentIntValue,
  minValue: 15,
  maxValue: 45,
  step: 15,
  onChanged: (value) => setState(() => _currentIntValue = value),
),
```
Please reopen if it still happens to you.
