### ISSUE TITLE
Dart 3 issue :The getter 'accentColor' isn't defined for the class 'ThemeData'.

### ISSUE THREAD

**Issue by aulimge** [MarcinusX/NumberPicker#143]
../../../.pub-cache/hosted/pub.dev/numberpicker-2.1.1/lib/src/numberpicker.dart:200:66: Error: The getter 'accentColor' isn't defined for the class 'ThemeData'.

**Comment by SiriusArtLtd** [comment]
this issue blocking  iOS build and it happens even if numberpicker package is not used directly, but if is used other package dependant from numberpicker

->  themeData.textTheme.headline5?.copyWith(color: themeData.accentColor);  

See https://docs.flutter.dev/release/breaking-changes/theme-data-accent-properties

Theme.of(context).accentColor;  to become  Theme.of(context).colorScheme.secondary;

**Comment by MarcinusX** [comment]
The issue should be fixed in 2.1.2
