### ISSUE TITLE
Cancel and Confirm

### ISSUE THREAD

**Issue by RobertBrunhage** [MarcinusX/NumberPicker#17]
How do I check if cancel and confirm?

I want to await the widget and if I press ok I want to keep doing the logic and if the user press cancel I want to stop the logic (with bool or something like that). But the cancel and confirm takes a widget. Why can I just not set logic in this?

I want to do something like this:

![image](https://user-images.githubusercontent.com/26344867/41583447-cc335e40-73a4-11e8-871a-9594b13a8cf6.png)

**Comment by MarcinusX** [comment]
Assuming you want to put in some sort of dialog, you can get the return value from that dialog. Having so, you can assume that if that value is `null`, user has canceled.

**Comment by RobertBrunhage** [comment]
Right now I am using the _intervalPicker as a dialog in the app, and if I press ok I want to keep the method going and cancel if not.

Will the value be null when canceled or will it go back to the previous state?

**Comment by MarcinusX** [comment]
Take a look at this example from readme:
```
void _showDialog() {
    showDialog<int>(
      context: context,
      builder: (BuildContext context) {
        return new NumberPickerDialog.decimal(
          minValue: 1,
          maxValue: 10,
          title: new Text("Pick a new price"),
          initialDoubleValue: _currentPrice,
        );
      }
    );.then((int value)) {
      if (value != null) {
        setState(() => _currentPrice = value);
      }
    });
  }
```
If user closes dialog, then `value` is null.

**Comment by RobertBrunhage** [comment]
Oh didn't know that, Thanks a lot for the help! :)

**Comment by MarcinusX** [comment]
Can I close it or you would like some more help? :)

**Comment by RobertBrunhage** [comment]
You can close! :)
