### ISSUE TITLE
Add property for number of values between min and max value

### ISSUE THREAD

**Issue by mnw007** [MarcinusX/NumberPicker#19]
It would be good if we can provide number of values between minimum value and maximum value.
For example , I have a range from 100 to 500 and I want to display only values that are multiple of 100, instead of the usual increment of 1.

**Comment by MarcinusX** [comment]
Hey man!
Yeah, it feels like a reasonable feature. At this moment I am too busy to do it, would you mind trying to implement it? :)

**Comment by mnw007** [comment]
Okay, I'll take that

**Comment by MarcinusX** [comment]
I've added step parameter to integer numberpicker. Would you like to check it out?
