### ISSUE TITLE
Document how to test NumberPicker in a widget test

### ISSUE THREAD

**Issue by zacps** [MarcinusX/NumberPicker#22]
I want to be able to create a test which taps on particular values in the numberpicker and checks to make sure they have the intended effect.

How can I scroll the relevant number into view and then tap it?

I don't want to just call the `onChanged` callback myself.

**Comment by MarcinusX** [comment]
Hey, good question!
I've added some basic tests, tell me if that works for you :)
https://github.com/MarcinusX/NumberPicker/blob/master/test/numberpicker_test.dart

**Comment by zacps** [comment]
That's perfect, thanks!
