### ISSUE TITLE
Step equal to 10 breaks on iOS emulator

### ISSUE THREAD

**Issue by alan16R** [MarcinusX/NumberPicker#23]
NumberPicker worked fine until I installed:

Flutter 0.7.3 • channel beta • https://github.com/flutter/flutter.git
Framework • revision 3b309bda07 (8 days ago) • 2018-08-28 12:39:24 -0700
Engine • revision af42b6dc95
Tools • Dart 2.1.0-dev.1.0.flutter-ccb16f7282

Now at least in the iOS emulator it does not seem to properly handle the 'mouse up' event when attempting to scroll.

**Comment by alan16R** [comment]
Closing this issue. Further investigation reveals that the behavior may not be due to the upgrade.

**Comment by MarcinusX** [comment]
So everything works fine? :)

**Comment by MarcinusX** [comment]
Hmm...  
I will try to investigate it in a couple days but if it happens only on iOS I am not sure if I will be able to do much.

**Comment by alan16R** [comment]
I’ll investigate further as well. I’ll deploy to iOS and see if the problem manifests on a real device and report back.

**Comment by MarcinusX** [comment]
Should work in version 1.7

**Comment by alan16R** [comment]
Thank you!

Tested on iOS and it works fine now.

Regards

Alan Chaney
