### ISSUE TITLE
Picker UI not being correctly redraw once initialValue property gets updated

### ISSUE THREAD

**Issue by wizche** [MarcinusX/NumberPicker#26]
I'm experiencing the following issue:
* In my model I set intialValue default to 1 (this property is mapped to the initialValue property of the picker widget)
* In my widget builder method I call an async method that will load some data and update this initialValue property
* I call notifyListeners/setState after the initialValue has been updated (async method finished)
* the picker widget is redraw but the "current" value is still the old one, we see that the value has been changed because is not green anymore, meaning that it took the new value but it didn't displayed correctly (see screenshot below)

Without calling the async method, initialValue defaults to one (in green):
![image](https://user-images.githubusercontent.com/1062939/45266228-f75cab00-b457-11e8-8c28-d5b09b2297d5.png)

When calling the async method and the intialValue changed to 6, the UI doesn't reflect the new value:
![image](https://user-images.githubusercontent.com/1062939/45266232-0e030200-b458-11e8-9a33-fc3c8255a489.png)

Thanks

**Comment by MarcinusX** [comment]
Hey, could you provide source code so I can reproduce the bug?

**Comment by wizche** [comment]
@MarcinusX hi, I was just looking at the NumberPicker code, I saw there is an animateInt method that scrolls to the right position. Am I suppose to call it manually when the initialValue changes?

**Comment by wizche** [comment]
Here a simple example where the initialValue is updated to 10 once you press the button, the pickerUI doesn't reflect the value though.

```dart
class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);
  final String title;
  @override
  _MyHomePageState createState() => new _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _initialValue = 5;

  @override
  Widget build(BuildContext context) {
    return new Scaffold(
      appBar: new AppBar(
        title: new Text(widget.title),
      ),
      body: new Center(
        child: new Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            NumberPicker.integer(
              initialValue: _initialValue,
              minValue: 0,
              maxValue: 100,
              step: 1,
              onChanged: (newValue) {},
            ),
          ],
        ),
      ),
      floatingActionButton: new FloatingActionButton(
        onPressed: () {
          setState(() {
            _initialValue = 10; // we update to 10, expect the picker to scroll to this value
          });
        },
        tooltip: 'Test',
        child: new Icon(Icons.add),
      ),
    );
  }
}
```

**Comment by MarcinusX** [comment]
Ok, so yeah, I think that calling `animateInt` is the way to go.

I cannot really imagine how I could animate to that changed value. I would have to run it on every build method asynchronously and I guess this is wouldn't be the cleanest approach.

I guess calling that method manually is not that bad, right?

**Comment by wizche** [comment]
I'm not very familiar yet with flutter/dart, how would you adapt my example to call animateInt when initialValue changes in a "clean" fashion?

Maybe whenn building the widget create a `scrollcontroller` with the right `initialScrollOffset`?

**Comment by MarcinusX** [comment]
It won't work like that because `initialScrollOffset` is _initial_. Meaning that it only matters when the widget is created, so it cannot be updated later on. (From what I know)

**Comment by wizche** [comment]
Maybe you want to keep this open as feature request? I'm probably not the only one that wants to set a value on the picker after an async operation (e.g. load last value from storage/API/...).

This is the (worst?) way I could think of for calling the animateInt(). I'm just calling a future on the builder method sometime in the future to be sure that the widget is "attached" already. How can I improve this?

```cs
new Future.delayed(new Duration(milliseconds: 100), () {
 try {
  picker.animateInt(model.value);
 } catch(e){
  print("Silently catching exception from picker ${e.toString()}"); // ScrollController not attached to any 
 scroll views
 }
});
```

**Comment by MarcinusX** [comment]
I don't see anything wrong about it. Why don't you like it?

**Comment by wizche** [comment]
because its a hack, it generates exception when the scrollcontroller is not attached, is non deterministic and even worst the code sucks 👎 
I think in the long run this should be handled internally by the picker state. When a new initialValue is being set the widget is being redraw and so are the scrollOffset recalculated

**Comment by MarcinusX** [comment]
Ok, I think you are right. :)
The only thing is that the main feature is actually picking a number by a user, not selecting it programmatically and my main concern is that this should not be disrupted by adding that option.

Would you consider proposing a solution in a pull request?

**Comment by wizche** [comment]
Since I'm not very experienced its probably better that someone else take this task :)

**Comment by praharshbhatt** [comment]
this issue still has not been solved?

**Comment by matteobertino** [comment]
Issue still present, this makes the widget unusable since there's no way for the user to select again the initialValue once changed.

**Comment by theflocco** [comment]
pls fix this.
Is it possible to get a list of currently rendered children, then iterate over them and call the function animateint?
Otherwise I don't know how to properly scroll to the changed value automatically

**Comment by tasibalint** [comment]
When is a fix comming, I understand it is a picker but when something on the widget changes and setState is called why is not the initial number set? or why cant we change the current value or something? is there a hack until this is resolved pretty annoying

**Comment by inforaudio** [comment]
I have the some problem.
In this ways the the widget cant no use.
