### ISSUE TITLE
Horizontal number picker

### ISSUE THREAD

**Issue by RaulMarquezInclan** [MarcinusX/NumberPicker#28]
Hi,

I would really like to see a scrollDirection property that when set to horizontal we can get a horizonal number picker.

Thanks for a great plugin!

**Comment by MarcinusX** [comment]
Wow, I have no idea how I missed that issue...

I will think about it ;)

**Comment by pedromassango** [comment]
Ops, I just dit it right now (https://github.com/MarcinusX/NumberPicker/pull/33) please merge my pull request
