### ISSUE TITLE
No call to onChanged when value == initialValue

### ISSUE THREAD

**Issue by boeledi** [MarcinusX/NumberPicker#3]
In case during the selection process you want to synchronize the value with another Widget (such as a Text), it should be convenient to also have a call to onChanged even if the current value == initialValue.

This could easily be solved by adding another option (e.g. *bool forceOnChanged* - default false).  If set to true, onChanged would be called in all circumstances.

**Comment by MarcinusX** [comment]
Sure, would you like to create pull request? :)

**Comment by boeledi** [comment]
If I may, yes please.  However I don't have the rights to create a new branch.

**Comment by MarcinusX** [comment]
You can create one by forking a repository and then creating a pull request.

**Comment by MarcinusX** [comment]
Closing for now, feel free to reopen if necessary.
