### ISSUE TITLE
Selected Values Not Highighted

### ISSUE THREAD

**Issue by rickspencer3** [MarcinusX/NumberPicker#34]
I am trying to incorporate you widget into my library. When a user designates an integer with a min and max value, I would like to return a number picker:

```dart
    if (fieldOptions != null) {
      if (fieldOptions["min"] != null && fieldOptions["max"] != null) {
        int value;
        int iv;
        initialValue == null ? iv = fieldOptions["min"] : iv = initialValue;
        return FormField(
          builder: (FormFieldState<int> state) {
            return NumberPicker.integer(
              initialValue: iv,
              maxValue: fieldOptions["max"],
              minValue: fieldOptions["min"],
              onChanged: (num val) {
                value = val;
              },
            );
          },
          onSaved: (int val) {
            this.onSaved(value);
          },
        );
      }
    }
```

The widget works perfectly in the form, except that the selected number is not highlighted except on first run. 

Here is the branch where I am working on this for reference:
https://github.com/rapido-mobile/rapido-flutter/blob/field_options/lib/src/typed_input_field.dart

**Comment by rickspencer3** [comment]
Ok, I figured out the problem. The problem is that NumberPicker is a stateless widget, and the highlighted value is the current value. So, in order to cause the highlighting to occur, you need to embed the NumberPicker within a stateless widget, and maintain the current value within a stateful widget, and call setState to rebuild that stateless widget. So, this code "works:"

```dart
class IntegerPickerFormField extends StatefulWidget {
  const IntegerPickerFormField({
    Key key,
    @required this.initialValue,
    @required this.fieldOptions,
    @required this.onSaved,
  }) : super(key: key);

  final Map<String, dynamic> fieldOptions;
  final Function onSaved;
  final int initialValue;

  @override
  IntegerPickerFormFieldState createState() {
    return new IntegerPickerFormFieldState();
  }
}

class IntegerPickerFormFieldState extends State<IntegerPickerFormField> {
  int _currentValue;

  @override
  void initState() {
    widget.initialValue == null
        ? _currentValue = widget.fieldOptions["min"]
        : _currentValue = widget.initialValue;
    super.initState();
  }

  @override
  Widget build(BuildContext context) {
    return FormField(
      builder: (FormFieldState<int> state) {
        return NumberPicker.integer(
          initialValue: _currentValue,
          maxValue: widget.fieldOptions["max"],
          minValue: widget.fieldOptions["min"],
          onChanged: (num val) {
            setState(() {
              _currentValue = val;
            });
          },
        );
      },
      onSaved: (int val) {},
    );
  }
}
```

The result of this is that the entire containing widget needs to be rebuilt on every onChanged event for the NumberPicker. If NumberPicker was a stateful widget, then only NumberPicker would have to rebuild itself on each change.

**Comment by MarcinusX** [comment]
Yes, but the idea was to give you, the developers, ability to use it as you want, you can always wrap this widget with StatefulWidget as you presented in your code :)

**Comment by dpedrinha** [comment]
Interesting. It means that somewhere inside the Widget, there should be a statefullwidget to handle this automatically and allow us to use it on a stateless widget without worrying about its state control. Sound pretty simple. Let me see....

**Comment by MarcinusX** [comment]
You can easily wrap the numberpicker in stateful widget and then not worry about state control ;)

**Comment by dpedrinha** [comment]
Yes, that's what I did. But...
You can ALSO easily wrap the numberpicker in stateful widget and then not worry about state control ;)
This way the plugin would work by its own and not rely on a "fix".
