### ISSUE TITLE
Padding numbers in integer picker

### ISSUE THREAD

**Issue by insin** [MarcinusX/NumberPicker#35]
Would it be possible to add some configuration for integer pickers to zero-pad the numbers displayed in the generated list items?

I have [a dialog widget](https://github.com/insin/tabata_timer/blob/f5e1b0b136393e090436dcfbd278906172965166/lib/widgets/durationpicker.dart) which uses a pair of `NumberPicker.integer`s to select minutes and seconds and gives you back a Duration object, which currently looks like this:

![qemu-system-x86_64_2019-02-02_03-26-04](https://user-images.githubusercontent.com/226692/52139063-c5fcaa00-269a-11e9-9394-77be9e6d60fa.png)

It would be nice to be able to pad the numbers less than 10 out with a zero so they match the way minutes and seconds are displayed elsewhere in the app, e.g. 00 : 09 in the example above.

**Comment by markflarup** [comment]
A quick fix (even though it is a really bad habit to change library files) is to change line 281 to `child: new Text(value.toString().padLeft(2, '0'), style: itemStyle),` inside `_integerInfiniteListView()`. The values will be stored without the padding 0, so you will have to take care of that as well.
