### ISSUE TITLE
Extra option to highlight the current selection rather than the initialValue

### ISSUE THREAD

**Issue by boeledi** [MarcinusX/NumberPicker#4]
As an example, I am using your NumberPicker to build a BirthDatePicker (made up of 3 NumberPickers - day, month, year).

Rather than having the initialValue(s) highlighted (*selectedStyle*), it would also be great to apply that style to the MiddleValue.

**Comment by MarcinusX** [comment]
I am not sure what you mean, can you give an example?

**Comment by boeledi** [comment]
For the moment, the initial value is highlighted via:

> //define special style for selected (middle) element
> final TextStyle itemStyle = value == selectedDecimalValue ? selectedStyle : defaultStyle;
> 

The idea is to:

* Give an additional option to highlight (or not) the initialValue
* Allow the user to add a "*decoration*" for the middle value

Based on your code, I simply added the following:

> 
> Widget _integerListView(ThemeData themeData) {
>     TextStyle defaultStyle = themeData.textTheme.body1;
>     TextStyle selectedStyle =
>         themeData.textTheme.headline.copyWith(color: themeData.accentColor);
> 
>     int itemCount = maxValue - minValue + 3;
> 
>     return new NotificationListener(
>       child: new Container(
>         height: _listViewHeight,
>         width: listViewWidth,
>         child: new Stack(
>           children: [
>             new ListView.builder(
>               controller: intScrollController,
>               itemExtent: itemExtent,
>               itemCount: itemCount,
>               itemBuilder: (BuildContext context, int index) {
>                 final int value = minValue + index - 1;
> 
>                 //define special style for selected (middle) element
>                 final TextStyle itemStyle =
>                     ((value == selectedIntValue)  && highlightInitialValue) ? selectedStyle : defaultStyle;
> 
>                 bool isExtra = index == 0 || index == itemCount - 1;
> 
>                 return isExtra
>                     ? new Container() //empty first and last element
>                     : new Center(
>                         child: new Text(value.toString(), style: itemStyle),
>                       );
>               },
>             ),
>             new Center(
>               child: new IgnorePointer(
>                               child: new Container(
>                   width: double.infinity,
>                   height: itemExtent,
>                   decoration: new BoxDecoration(
>                     border: new Border(
>                       top: new BorderSide(
>                         style: BorderStyle.solid,
>                         color: Colors.black26,
>                       ),
>                       bottom: new BorderSide(
>                         style: BorderStyle.solid,
>                         color: Colors.black26,
>                       ),
>                     ),
>                   ),
>                 ),
>               ),
>             ),
>           ],
>         ),
>       ),
>       onNotification: _onIntegerNotification,
>     );
>   }
> 

which gives me a way of "*highlighting*" the central value.

Of course, we could also think of letting the developer pass his own "*decoration*", in such a case, if passed it is used as *decoration:* of the Container, otherwise, it uses the default (no decoration).

This is just an idea.

**Comment by MarcinusX** [comment]
Ok, it took me a while but I understand. I like it!
In my opinion, the best approach would be to add 2 parameters:
- `{bool highlightSelectedValue = true}`
- `{Decoration selectedValueDecoration}`

If I understand correctly this is what you mean, right?
If so, would you be willing to create a pull request for that? I would really appreciate it :)

**Comment by rickspencer3** [comment]
A possibly different approach to the API would be to have selecteValueDecoration be optional and supply a default decoration. Users can supply their own decoration, or supply null if for some reason they don't want any decoration.
