### ISSUE TITLE
picker numbers misaligned when not using AppBar

### ISSUE THREAD

**Issue by dvorapa** [MarcinusX/NumberPicker#43]
There is one extra number shown when AppBar is missing, the center is shifted above and it is not clear, which of the two middle options is the chosen one.

**Comment by MarcinusX** [comment]
Can you provide code and screenshot? :)

**Comment by dvorapa** [comment]
I'm out of my PC for August, but it should be easily reproducible:

```
  $ flutter create test
  $ nano test/lib/main.dart
  now remove appBar and add some sample NumberPicker into body
  see misaligned numbers
```

**Comment by MarcinusX** [comment]
Cannot reproduce. Will reopen if someone can reproduce/

**Comment by sisierra** [comment]
We are currently facing the same issue.
As soon as we are setting extendBodyBehindAppBar=true. The Numberpcker are misaligned and onChangedMethod delivers wrong values.
Below the example code, you see two screenshots, the first shows correct behavior and the second screenshot shows the behavior when extendBodyBehindAppBar=true and the described issue.


`import 'package:flutter/material.dart';
import 'package:numberpicker/numberpicker.dart';

class TestNumberPickerScreen extends StatefulWidget {
  TestNumberPickerScreen({Key key, this.title}) : super(key: key);
  final String title;

  @override
  _TestNumberPickerScreenState createState() => _TestNumberPickerScreenState();
}

class _TestNumberPickerScreenState extends State<TestNumberPickerScreen> {

  int _selectedValue;

  @override
  void initState() {
    _selectedValue = 0;
    super.initState();
  }
  @override
  Widget build(BuildContext context) {
    return Scaffold(
          backgroundColor: Colors.lightGreen,
            //extendBodyBehindAppBar: true,
            appBar: new AppBar(
                title: new Row(
                    mainAxisAlignment: MainAxisAlignment.spaceBetween,
                    children: <Widget>[
                      Text('NumberPickerTest'),
                    ]),
            ),
            body: Container(
                child: Center(
                    child: new Column(
                        mainAxisAlignment: MainAxisAlignment.center,
                        mainAxisSize: MainAxisSize.max,
                        crossAxisAlignment: CrossAxisAlignment.center,
                        children: <Widget>[
                          SizedBox(height:50),
                          new NumberPicker.integer(
                              initialValue: 30,
                              minValue: 0,
                              step: 1,
                              maxValue: 50,
                              onChanged: (value) {
                                setState(() {
                                  _selectedValue = value;
                                });
                              }
                          ),
                          SizedBox(height:50),
                          Text('Selected Value:'+_selectedValue.toString())
                        ]))));
  }
}`
![WhatsApp Image 2020-12-23 at 12 42 45(1)](https://user-images.githubusercontent.com/8349887/102992909-7fc5c380-451c-11eb-82f9-6bb27d495fe0.jpeg)
![WhatsApp Image 2020-12-23 at 12 42 45](https://user-images.githubusercontent.com/8349887/102992912-805e5a00-451c-11eb-9d6c-28b28cf902e9.jpeg)

**Comment by sisierra** [comment]
# Can someone take a look on the latest actions on my response, or otherwise I would create a new issue

**Comment by MarcinusX** [comment]
Crap, you're right. Super weird...
