### ISSUE TITLE
Bug in NumberPicker.horizontal

### ISSUE THREAD

**Issue by delef** [MarcinusX/NumberPicker#52]
I can't select the last 3 items. constantly rolls back.

Example:
![ezgif-1-337adf32a651](https://user-images.githubusercontent.com/2103263/62720484-c6dc1300-ba12-11e9-9aca-62575ba40172.gif)

Code for reproduce:
```
NumberPicker.horizontal(
  initialValue: 5,
  minValue: 1,
  maxValue: 10,
  onChanged: (num newValue) {
    // save
  },
)
```

**Comment by delef** [comment]
@pedromassango help me please

**Comment by delef** [comment]
normally works only with `this.itemExtent = 100.0`, but this is too far a distance.

**Comment by MarcinusX** [comment]
Hi @delef,
In general, NumberPicker is designed to display only 3 numbers at once, so if you are having let's say `itemExtent = 50`, then you should make wrap numberpicker in for example `SizedBox(width: 150)`.

I can see it more as Feature request for being able to see more than 3 numbers, but I cannot tell you any date on when it will be implemented.

**Comment by pedromassango** [comment]
> Hi @delef,
> In general, NumberPicker is designed to display only 3 numbers at once, so if you are having let's say `itemExtent = 50`, then you should make wrap numberpicker in for example `SizedBox(width: 150)`.
> 
> I can see it more as Feature request for being able to see more than 3 numbers, but I cannot tell you any date on when it will be implemented.

This make sense. So @MarcinusX any tip about how we can avoid that in the libary?

**Comment by DylanoH** [comment]
Any update on this?

**Comment by MarcinusX** [comment]
It should work now in version 2.1.0. Please make sure that `itemWidth * itemCount < screenWidth`. 
![image](https://user-images.githubusercontent.com/16286046/114515842-1689cd80-9c3d-11eb-94a0-bd3273554719.png)
I'm closing the issue. Feel free to reopen if it still occurs.

**Comment by JigneshPatel23** [comment]
I am struggling to select last value..
