### ISSUE TITLE
Add TextStyles for NumberPicker

### ISSUE THREAD

**Issue by adityadroid** [MarcinusX/NumberPicker#53]
Is it possible to add an option to supply custom TextStyles? I know that number picker picks the TextStyles from ThemeData.

**Comment by henriquearthur** [comment]
You can override the theme for a specific widget like NumberPicker like this:

```
Theme(
      data: ThemeData(
        textTheme: TextTheme(
          body1: Theme.of(context).textTheme.body1.copyWith(fontSize: 14.0),
          headline:
              Theme.of(context).textTheme.headline.copyWith(fontSize: 16.0),
        ),
      ),
      child: NumberPicker.integer(
        initialValue: _currentValue,
        minValue: 0,
        maxValue: 10,
        onChanged: (newValue) => setState(() => _currentValue = newValue),
      ),
    );
```

`body1` is for unselected numbers and `headline` is for selected number.

**Comment by adityadroid** [comment]
> You can override the theme for a specific widget like NumberPicker like this:
> 
> ```
> Theme(
>       data: ThemeData(
>         textTheme: TextTheme(
>           body1: Theme.of(context).textTheme.body1.copyWith(fontSize: 14.0),
>           headline:
>               Theme.of(context).textTheme.headline.copyWith(fontSize: 16.0),
>         ),
>       ),
>       child: NumberPicker.integer(
>         initialValue: _currentValue,
>         minValue: 0,
>         maxValue: 10,
>         onChanged: (newValue) => setState(() => _currentValue = newValue),
>       ),
>     );
> ```
> 
> `body1` is for unselected numbers and `headline` is for selected number.

Thanks. Didn't knew about this workaround.

**Comment by MarcinusX** [comment]
WOW, I didn't know about it either!
