### ISSUE TITLE
A RenderFlex overflowed by 8.0 pixels on the right.

### ISSUE THREAD

**Issue by rayzor** [MarcinusX/NumberPicker#64]
Overflow of 8px on 3.7 inch screen. 
Any suggestions please  ... tried SizedBox but not successful.
- otherwise NumberPicker works very well .. . excellent piece of work - thanks all.

/try Example code from github and suggested SizedBox wrap solution to overflow....
  double _currentPrice = 1.0;

  void _showDialog() {
    showDialog<double>(
        context: context,
        builder: (BuildContext context) {

        return  SizedBox (
           // width: 200, // fail Overflow 8px
            width: 30, // fail overflow 8px
          child: new NumberPickerDialog.decimal(
            minValue: 1,
            maxValue: 10,
            title: new Text("Pick a new price"),
            initialDoubleValue: _currentPrice,
          )
        );
        }
    ).then((double value) {
      if (value != null) {
        setState(() => _currentPrice = value);
      }
    });
  }

![Screenshot_1577164344](https://user-images.githubusercontent.com/28950/71394796-06467d00-260b-11ea-93c9-8c26400dfdab.png)

**Comment by MarcinusX** [comment]
We dropped support for dialogs, so I'm closing this one.
