### ISSUE TITLE
Exception when use NumberPickerDialog.integer()

### ISSUE THREAD

**Issue by polis** [MarcinusX/NumberPicker#65]
Hi,

Thanks for that lib! 

I used the NumberPickerDialog in my code. 
After select the number and press ok It shows error in console:

E/flutter (28635): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: 'package:flutter/src/widgets/scroll_controller.dart': Failed assertion: line 150 pos 12: '_positions.isNotEmpty': ScrollController not attached to any scroll views.
E/flutter (28635): #0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:42:39)
E/flutter (28635): #1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:38:5)
E/flutter (28635): #2      ScrollController.animateTo (package:flutter/src/widgets/scroll_controller.dart:150:12)
E/flutter (28635): #3      NumberPicker._animate (package:numberpicker/numberpicker.dart:561:22)
E/flutter (28635): #4      NumberPicker.animateIntToIndex (package:numberpicker/numberpicker.dart:202:5)
E/flutter (28635): #5      NumberPicker.animateInt (package:numberpicker/numberpicker.dart:197:5)
E/flutter (28635): #6      _TimerSettings._showIntDialog.<anonymous closure> (package:intervaltimer/screens/settings/timer_settings_page.dart:69:29)
E/flutter (28635): #7      _rootRunUnary (dart:async/zone.dart:1134:38)
E/flutter (28635): #8      _CustomZone.runUnary (dart:async/zone.dart:1031:19)
E/flutter (28635): #9      _FutureListener.handleValue (dart:async/future_impl.dart:140:18)
E/flutter (28635): #10     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:682:45)
E/flutter (28635): #11     Future._propagateToListeners (dart:async/future_impl.dart:711:32)
E/flutter (28635): #12     Future._completeWithValue (dart:async/future_impl.dart:526:5)
E/flutter (28635): #13     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:556:7)
E/flutter (28635): #14     _rootRun (dart:async/zone.dart:1126:13)
E/flutter (28635): #15     _CustomZone.run (dart:async/zone.dart:1023:19)
E/flutter (28635): #16     _CustomZone.runGuarded (dart:async/zone.dart:925:7)
E/flutter (28635): #17     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:965:23)
E/flutter (28635): #18     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
E/flutter (28635): #19     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
E/flutter (28635):

**Comment by jefferywunady** [comment]
Getting the same error. Any solution to this yet?

**Comment by jefferywunady** [comment]
Turns out, if you remove         

`integerNumberPicker.animateInt(value);`

from your code, it works now.
