### ISSUE TITLE
Is it possible to accept a list of strings instead of numbers  for example apple, ball, cat etc and define the the length. does anyone know how to tweak this

### ISSUE THREAD

**Issue by samsheldin** [MarcinusX/NumberPicker#66]

**Comment by MarcinusX** [comment]
I think the best way would be to use just a ListView or maybe [ListWheelScrollView](https://www.youtube.com/watch?v=dUhmWAz4C7Y). 
I don't think numberpicker should support it.
If it helps you, feel free to copy the code and alter it for your use. :)
