### ISSUE TITLE
textMapper

### ISSUE THREAD

**Issue by Hatesh8** [MarcinusX/NumberPicker#71]
Can you please give me a hint or code to use textMapper?
I want to achieve some things like this.

![image](https://user-images.githubusercontent.com/18635520/81622590-cbeb4a00-940a-11ea-809e-0e6526bcb267.png)

**Comment by golnarSheikhBahaie** [comment]
me too .. could you find any thing yet ?

**Comment by Hatesh8** [comment]
@golnarSheikhBahaie  I did not find the solution for it yet but what I have done is I just have customized it as per my need

**Comment by davelnewton** [comment]
@Hatesh8 `textMapper` is just a function that takes a string containing the value and returns a string, so:

`textMapper: (s) => `$s Kg`,`

**Comment by Hatesh8** [comment]
> @Hatesh8 `textMapper` is just a function that takes a string containing the value and returns a string, so:
> 
> `textMapper: (s) => '$s Kg',`
> 
> FWIW I found this by searching the repo for `TextMapper`, found its `typedef`, and that's about all it took.

Thank you so much, I finally have done with it.
