### ISSUE TITLE
customize font size or style

### ISSUE THREAD

**Issue by niypoo** [MarcinusX/NumberPicker#72]
How we can customize or change font style of number

**Comment by ab-dev-github** [comment]
Looking for the same info. Please share if anyone know how to do it.

**Comment by golnarSheikhBahaie** [comment]
hi guys .. does any one have idea ?? im looking for it to change number into persian ...

**Comment by golnarSheikhBahaie** [comment]
> Looking for the same info. Please share if anyone know how to do it.

guys in find some solution for it 
if you need to for example change the font  u can apply the font family to whole of your build widget .
like this 
MaterialApp(
  title: 'Custom Fonts',
  // Set Raleway as the default app font.
  theme: ThemeData(fontFamily: 'Raleway'),
  home: MyHomePage(),
);
for more info to how to do this u can check :
https://flutter.dev/docs/cookbook/design/fonts
and you can easily change the font style ;)

**Comment by davelnewton** [comment]
But only for the entire app; That's not sufficient if you need to enlarge just the selected value etc.

**Comment by Athu135** [comment]
in the code you can change the style of the text for eg:
 Widget _integerListView(ThemeData themeData) {

    TextStyle defaultStyle = themeData.textTheme.bodyText2;
    TextStyle selectedStyle =
        themeData.textTheme.headline6.copyWith(color: themeData.accentColor);

    var listItemCount = integerItemCount + 2;

    return Listener(
      onPointerUp: (ev) {
        ///used to detect that user stopped scrolling
        if (intScrollController.position.activity is HoldScrollActivity) {
          animateInt(selectedIntValue);
        }
      },
      child: NotificationListener(
        child: Container(
          height: listViewHeight,
          width: listViewWidth,
          child: Stack(
            children: <Widget>[
              ListView.builder(
                scrollDirection: scrollDirection,
                controller: intScrollController,
                itemExtent: itemExtent,
                itemCount: listItemCount,
                cacheExtent: _calculateCacheExtent(listItemCount),
                itemBuilder: (BuildContext context, int index) {
                  final int value = _intValueFromIndex(index);

                  //define special style for selected (middle) element
                  final TextStyle itemStyle =
                      value == selectedIntValue && highlightSelectedValue
                          ? selectedStyle
                          : defaultStyle;

                  bool isExtra = index == value || index == listItemCount - value;

                  return isExtra
                      ? Container()
                      :Center(
                          child: Text(
                            getDisplayedValue(value),
                            **style: TextStyle(color: themeData.colorScheme.secondary,fontSize: 20),**
                          ),
                        );
                },
              ),
              _NumberPickerSelectedItemDecoration(
                axis: scrollDirection,
                itemExtent: itemExtent,
                decoration: decoration,
              ),
            ],
          ),
        ),
        onNotification: _onIntegerNotification,
      ),
    );
  }

the bold text is edited

**Comment by davelnewton** [comment]
@Athu135 Well yeah, I could fork and add whatever I wanted--that's not quite the configurability I had in mind.

**Comment by MarcinusX** [comment]
I think #69 completed this. Feel free to reopen if disagree.
