### ISSUE TITLE
Unexpected padding in ListView results off position of item

### ISSUE THREAD

**Issue by lzhuor** [MarcinusX/NumberPicker#74]
### Problem
For Scaffold without an app bar, ListView has an inner padding on the top which results item positions are off. Related to [Flutter Issues #14842]( https://github.com/flutter/flutter/issues/14842)

![image](https://user-images.githubusercontent.com/14172220/82800564-80c34380-9eae-11ea-9853-45be340e0f9f.png)

### Solution:
Add `MediaQuery.removePadding()` for `ListView.builder` in `numberpicker.dart`.

**Comment by pbouttier** [comment]
Same problem in my side.

I have fixed it by adding a SafeArea on top of my widgets

**Comment by lzhuor** [comment]
@pbouttier Are you using an iPhoneX and above? `SafeArea` didn't solve the problem for me when it's on iPhone 8.
