### ISSUE TITLE
Can't change font size

### ISSUE THREAD

**Issue by geekz-reno** [MarcinusX/NumberPicker#88]
Hi, is there options that i missing? i can change selected color, but the font size seems not changes , font size fallback to default size if i put selectedTextStyle options. 

```dart
NumberPicker.integer(
  initialValue: controller.params().paxAdult,
  minValue: 0,
  maxValue: 9,
  selectedTextStyle: TextStyle(
    fontSize: 16.0,
    color: Color(0xFF4c934c)
  ),
  onChanged: (value) {
    controller.setPaxNumber(value, 0);
  },
)
```

**Comment by MarcinusX** [comment]
It works for me on version 2.1.0. I'm closing this issue but if it still occurs to you, feel free to reopen.

**Comment by ShivamJaglan** [comment]
same issue

**Comment by MarcinusX** [comment]
Could you show me how it looks like with for example fontSize: 20?

**Comment by ShivamJaglan** [comment]
Just updated my lib ! Works like breeze now! Thanks @MarcinusX
