### ISSUE TITLE
Would love to see this updated to null safety

### ISSUE THREAD

**Issue by tadaspetra** [MarcinusX/NumberPicker#89]

**Comment by nilsreichardt** [comment]
Here are some helpful resources:
* [How to migrate Dart packages to null safety](https://youtu.be/eBr5tlumwlg)
* [Announcing Dart null safety beta](https://medium.com/dartlang/announcing-dart-null-safety-beta-87610fee6730)

**Comment by MarcinusX** [comment]
I have finally found some time to refactor the whole package. It was nearly impossible to work on the code which remembered the `new` keyword :D

@tadaspetra, @nilsreichardt would you mind cloning the PR and verifying that it works? As I don't use the package at the moment and it's hard for me to come up with the use cases.
