### ISSUE TITLE
Error::Documentation

### ISSUE THREAD

**Issue by hassanrehman01398** [MarcinusX/NumberPicker#91]
This code will return errror     showDialog<int>(
      context: context,
      builder: (BuildContext context) {
        return new NumberPickerDialog.decimal(
          minValue: 1,
          maxValue: 10,
          title: new Text("Pick a new price"),
          initialDoubleValue: _currentPrice,
        );
      }
    ).then((int value)) {
      if (value != null) {
        setState(() => _currentPrice = value);
      }
    });
so please change the parameters to decimal.

**Comment by MarcinusX** [comment]
I have removed it from the docs, show I think we can close this issue. Feel free to reopen if disagree. :)
