### ISSUE TITLE
NumberPicker in Dialog always returns to initialValue

### ISSUE THREAD

**Issue by guillermin** [MarcinusX/NumberPicker#96]
I put a NumberPicker inside a SimpleDialog and whenever I scroll it it immediately scrolls back to the initial value. If I put the NumberPicker directly on the page it works as expected, so it seems to be something about being in a Dialog.
Checking the code history I saw that there used to be a NumberPickerDialog and it has been removed. Is it possible to have a NumberPicker in a Dialog now? If so, could you please provide an example of a working NumberPicker in a Dialog?

**Comment by MarcinusX** [comment]
Can you show example code?

**Comment by guillermin** [comment]
I've ended up placing the NumberPicker directly on the page so it's OK.

The relevant code was this:

```dart
showDialog(
  context: context,
  builder: (BuildContext context) => SimpleDialog(
    title: Text('Edit Exercise'),
    children: [
      ListTile(
        leading: Padding(
          padding: EdgeInsets.only(top: 25),
          child: Icon(Icons.snooze)),
        title: NumberPicker(
          itemHeight: 30,
          value: _prelude,
          minValue: 1,
          maxValue: 600,
          textMapper: textMapper,
          onChanged: (value) => setState(() => _prelude = value))),
      Divider(),
      ListTile(
        leading: Icon(Icons.fitness_center),
        title: TextFormField(
          textAlign: TextAlign.center,
          initialValue: title,
        )),
      Divider(),
      ListTile(
        leading: Padding(
          padding: EdgeInsets.only(top: 25),
          child: Icon(Icons.timer)),
        title: NumberPicker(
          itemHeight: 30,
          value: _duration,
          minValue: 1,
          maxValue: 600,
          textMapper: textMapper,
          onChanged: (value) => setState(() => _duration = value))),
      Padding(
          padding: EdgeInsets.fromLTRB(20, 20, 20, 0),
          child: ElevatedButton(
            onPressed: () {},
            child: Text('Save')))
      ]));
});
```

**Comment by guillermin** [comment]
I'm going to close the issue because I was clearly mistaken in my use of SimpleDialog and that is probably why it wasn't working. I should have used an AlertDialog, but since I've decided to go in another direction it doesn't even matter anymore.
