### ISSUE TITLE
Add infiniteLoop to 2.0.x

### ISSUE THREAD

**Issue by mmaia** [MarcinusX/NumberPicker#97]
I am using your library for a project and it's very nice but I was upgrading to use it with null safety from v 1.3 to v2.0 and I noticed the infinite loop functionality is gone. Do you have plans to reimplement it? 

Is there a specific reason to have it removed?

**Comment by MarcinusX** [comment]
It was because InfiteListView package wasn't migrated to null safety and I had only one day to work on numberpicker's migration.
Since it is now migrated I can add it the package. :)
